{% set name = "parcels" %}
{% set version = "1.1.0" %}
{% set sha256 = "7456ae52c81376ab2af99852245f813a74e6f3eba3f213907d2e1bc92b378b75" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/oceanparcels/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
<<<<<<< HEAD
  number: 1
=======
  number: 2
>>>>>>> conda-forge/master
  script:
    - "{{ PYTHON }} setup.py bdist_wheel --dist-dir=dist"
    - "{{ PYTHON }} -m pip install --find-links=dist --no-deps --ignore-installed --no-cache-dir -vvv {{ name }}"

requirements:
  build:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - wheel
  run:
    - python
    - cachetools >=1.0.0
    - cgen
    - enum34  # [py2k]
    - ffmpeg >=3.2.3,<3.2.6
    - gcc_linux-64  # [linux]
    - clang_osx-64  # [osx]
    - m2w64-toolchain  # [win]
    - matplotlib 2.0.2
    - netcdf4 >=1.1.9
    - numpy >=1.9.1
    - progressbar2
    - pymbolic
    - python-dateutil
    - scipy >=0.16.0
    - six >=1.10.0
    - xarray >=0.5.1

test:
  imports:
    - parcels
    - parcels.scripts
    - parcels.kernels
    - parcels.tools

about:
  home: http://github.com/OceanParcels/parcels
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Probably A Really Computationally Efficient Lagrangian Simulator'

  description: |
    Parcels (Probably A Really Computationally Efficient Lagrangian Simulator)
    is a set of Python classes and methods to create customisable particle 
    tracking simulations using output from Ocean Circulation models. 
    Parcels can be used to track passive and active particulates such as 
    water, nutrients, plankton, plastic and fish.
  doc_url: http://oceanparcels.org/
  dev_url: https://github.com/OceanParcels/parcels

extra:
  recipe-maintainers:
    - erikvansebille
    - delandmeterp
    - willirath
