{% set name = "parcels" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oceanparcels/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 069051f3cf30bda3f3c301682855ec0b40e00b3ebce0f20f7f10f765465eb308

build:
  number: 2
  skip: True  # [py<38]
  script:
    - {{ PYTHON }} setup.py bdist_wheel --dist-dir=dist
    - {{ PYTHON }} -m pip install --find-links=dist --no-deps --ignore-installed --no-cache-dir -vvv {{ name }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - wheel
  run:
    - python
    - cftime
    - cgen
    - dask
    - enum34  # [py2k]
    - gcc_linux-64  # [linux]
    - clang_osx-64  # [osx]
    - m2w64-toolchain  # [win]
    - matplotlib-base >=2.0.2
    - netcdf4 >=1.1.9
    - numpy >=1.9  # [linux64 or osx]
    - numpy >=1.11  # [win]
    - platformdirs
    - psutil
    - pymbolic
    - pytest
    - scipy >=0.16.0
    - tqdm
    - xarray >=0.10.8
    - zarr >=2.11.0

test:
  imports:
    - parcels
  commands:
    - curl wget https://raw.githubusercontent.com/OceanParcels/parcels/master/docs/examples/example_peninsula.py > example_peninsula.py
    - python example_peninsula.py

about:
  home: http://github.com/OceanParcels/parcels
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Probably A Really Computationally Efficient Lagrangian Simulator

  description: |
    Parcels (Probably A Really Computationally Efficient Lagrangian Simulator)
    is a set of Python classes and methods to create customisable particle 
    tracking simulations using output from Ocean Circulation models. 
    Parcels can be used to track passive and active particulates such as 
    water, nutrients, plankton, plastic and fish.
  doc_url: http://oceanparcels.org/
  dev_url: https://github.com/OceanParcels/parcels

extra:
  recipe-maintainers:
    - erikvansebille
    - delandmeterp
    - ckehl
    - willirath
