travis:
  secure:
    BINSTAR_TOKEN: fwMRNA6Q1ZKOVFuOy1CfNKofw76U0jvXooOP48FAMCrWLA6flzZuLyhJHSCiBfgK+xynDNwFYjPaxo732lZvjqYNyakJHm39EGHKcTmqiBwan6Vm+QtJJKSsxy4GB3i0USt6Pj/U88DZS6l9iZsObUOudG8AsDrhxT9QhSfNAxVthgIOeKToTC4Z8U1LTDTKE/TYCy8IMjUEnNKJDcnzA50bm7eZYEyiE7TKbZtqPkJDDUglU6TsVjyio2f8AGR813HV8Li4cWzsjU9S0ydOBUSmUj8teAzaWSXx801KkDmCpBBLKbCC7aNOFdaNUpGt7ed83dm3KmP00Wuq7BmIvB+EgwHPVNGuq+EO51apycn//vOLZFXl0ZP8Lgi3e4p+kB08bynm7wBrF2gro+dymUUqecljO9m+iUomCx0+3O8UKATvvsOxC7UpaCokK9A+WlPeUi2x4+1E2Yz/ZCcDFXisCv/n3QkUjTodMWJalJzv1L6cVI46dy8cZDchTPtds300GiWxEtIdoeTi7MGhMOXrz/oyBuMhOAIhfcaknnLt8ACEwKHLcGuW5nipoyzjmVTzJDo1hxPkImYYUvmTYJ8VmtuydO6T2saAt5s2HayATDv8x3iFw/6onT6EQ1UkxJX3gU65TTHNRyzw7hrVQvtHAUE2cet7wt9i8M0IRh4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
